"""
Sequence generators.

Sequences combine multiple tool procedures into a single callable task.
They appear in the pendant menu alongside individual tools and call
existing Py2 procedures in order.
"""


def generate_seq_bed_clean(params: dict) -> str:
    """
    Generate SeqBedClean procedure.
    
    Bed cleaning sequence:
    1. Run vacuum pattern (Py2Vacuum)
    2. Run polish pattern (Py2Polish)
    
    This sequence uses existing parameters from the DB/frontend for each tool.
    """
    proc = '''
    PROC SeqBedClean()
        ! SeqBedClean - Bed Cleaning Sequence
        ! Runs: Vacuum -> Polish
        ! Generated by Onyx Toolpath Generator v2
        
        TPWrite "========================================";
        TPWrite "SeqBedClean: Starting Bed Clean Sequence";
        TPWrite "========================================";
        TPWrite "Step 1: Vacuum";
        TPWrite "Step 2: Polish";
        TPWrite "========================================";
        
        ! Step 1: Vacuum the bed
        TPWrite "SeqBedClean: Starting vacuum...";
        Py2Vacuum;
        TPWrite "SeqBedClean: Vacuum complete";
        
        ! Step 2: Polish the bed
        TPWrite "SeqBedClean: Starting polish...";
        Py2Polish;
        TPWrite "SeqBedClean: Polish complete";
        
        TPWrite "========================================";
        TPWrite "SeqBedClean: SEQUENCE COMPLETE";
        TPWrite "========================================";
        
    ERROR
        TPWrite "SeqBedClean ERROR: " \\Num:=ERRNO;
        RAISE;
    ENDPROC
'''
    return proc
