# Generated by Django 5.2.9 on 2026-01-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPathParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_x', models.IntegerField(default=5900, help_text='Panel length X (mm)')),
                ('panel_y', models.IntegerField(default=2200, help_text='Panel width Y (mm)')),
                ('panel_z', models.IntegerField(default=150, help_text='Panel height Z (mm)')),
                ('polisher_step', models.IntegerField(default=450, help_text='Polisher step (mm)')),
                ('pan_step', models.IntegerField(default=600, help_text='Pan step (mm)')),
                ('helicopter_step', models.IntegerField(default=600, help_text='Helicopter step (mm)')),
                ('vib_screed_speed', models.IntegerField(default=100, help_text='Vibrating screed speed (mm/s)')),
                ('z_offset', models.IntegerField(default=0, help_text='Z offset (mm)')),
                ('datum_offset_x', models.IntegerField(default=1100, help_text='Datum offset X (mm)')),
                ('datum_offset_y', models.IntegerField(default=600, help_text='Datum offset Y (mm)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Toolpath Parameters',
                'verbose_name_plural': 'Toolpath Parameters',
            },
        ),
    ]
