# Generated by Django 5.2.9 on 2026-01-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='screed_angle_offset',
            field=models.IntegerField(default=0, help_text='Screed angle offset (degrees)'),
        ),
    ]
