# Generated by Django 5.2.9 on 2026-01-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0002_toolpathparameters_screed_angle_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_pattern',
            field=models.CharField(default='serpentine', help_text='Vacuum pattern', max_length=50),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_speed',
            field=models.IntegerField(default=100, help_text='Vacuum speed (mm/s)'),
        ),
    ]
