# Generated by Django 5.2.9 on 2026-01-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0003_toolpathparameters_vacuum_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_approach_speed',
            field=models.IntegerField(default=20, help_text='Polisher approach speed (mm/s)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_force_change',
            field=models.IntegerField(default=75, help_text='Polisher force change (N)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_motion_force',
            field=models.IntegerField(default=130, help_text='Polisher motion force (N)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_retract_speed',
            field=models.IntegerField(default=50, help_text='Polisher retract speed (mm/s)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_start_force',
            field=models.IntegerField(default=140, help_text='Polisher start force (N)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_step',
            field=models.IntegerField(default=450, help_text='Vacuum step (mm)'),
        ),
    ]
