# Generated by Django 5.2.9 on 2026-01-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0004_toolpathparameters_polisher_approach_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_blade_speed',
            field=models.IntegerField(default=70, help_text='Pan blade speed (RPM, 40-140)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_travel_speed',
            field=models.IntegerField(default=100, help_text='Pan travel speed (mm/s)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_z_offset',
            field=models.IntegerField(default=250, help_text='Pan Z offset (mm, -200 to 200)'),
        ),
    ]
