# Generated by Django 5.2.9 on 2026-01-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0005_toolpathparameters_pan_blade_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_blade_angle',
            field=models.IntegerField(default=0, help_text='Helicopter blade angle (degrees, 0-12)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_blade_speed',
            field=models.IntegerField(default=70, help_text='Helicopter blade speed (RPM)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_force',
            field=models.IntegerField(default=200, help_text='Helicopter force (N, 100-500)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_travel_speed',
            field=models.IntegerField(default=40, help_text='Helicopter travel speed (mm/s)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_z_offset',
            field=models.IntegerField(default=0, help_text='Helicopter Z offset (mm, -50 to 400)'),
        ),
    ]
