# Generated by Django 5.2.9 on 2026-01-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0006_toolpathparameters_heli_blade_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_z_offset',
            field=models.IntegerField(default=0, help_text='Polisher Z offset (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='screed_z_offset',
            field=models.IntegerField(default=0, help_text='Screed Z offset (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_z_offset',
            field=models.IntegerField(default=0, help_text='Vacuum Z offset (mm)'),
        ),
    ]
