# Generated by Django 5.2.9 on 2026-01-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0007_toolpathparameters_polisher_z_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='serpentine_direction',
            field=models.IntegerField(default=1, help_text='Initial sweep direction: 1=left-to-right, -1=right-to-left'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='serpentine_offset_x',
            field=models.IntegerField(default=100, help_text='Serpentine X offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='serpentine_offset_y',
            field=models.IntegerField(default=100, help_text='Serpentine Y offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='serpentine_start_bottom',
            field=models.BooleanField(default=False, help_text='Start at bottom (True) or top (False)'),
        ),
    ]
