# Generated by Django 5.2.9 on 2026-01-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0008_toolpathparameters_serpentine_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='datum_offset_x',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='datum_offset_y',
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='bed_datum_x',
            field=models.IntegerField(default=1100, help_text='Bed datum offset X (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='bed_datum_y',
            field=models.IntegerField(default=600, help_text='Bed datum offset Y (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='bed_length_x',
            field=models.IntegerField(default=12000, help_text='Bed length X (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='bed_width_y',
            field=models.IntegerField(default=3200, help_text='Bed width Y (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='panel_datum_x',
            field=models.IntegerField(default=0, help_text='Panel datum offset X (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='panel_datum_y',
            field=models.IntegerField(default=0, help_text='Panel datum offset Y (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_workzone',
            field=models.CharField(default='panel', help_text='Vacuum workzone: panel or bed', max_length=20),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='z_offset',
            field=models.IntegerField(default=0, help_text='Z offset (mm) - applies to all workzones'),
        ),
    ]
