# Generated by Django 5.2.9 on 2026-01-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0009_remove_toolpathparameters_datum_offset_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_force',
            field=models.IntegerField(default=50, help_text='Vacuum target force (N, 10-150)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_z_max',
            field=models.IntegerField(default=50, help_text='Vacuum max Z from surface (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_z_min',
            field=models.IntegerField(default=-20, help_text='Vacuum min Z from surface (mm)'),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='panel_datum_x',
            field=models.IntegerField(default=1100, help_text='Panel datum offset X (mm)'),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='panel_datum_y',
            field=models.IntegerField(default=600, help_text='Panel datum offset Y (mm)'),
        ),
    ]
