# Generated by Django 5.2.9 on 2026-01-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0010_toolpathparameters_vacuum_force_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_force_enabled',
            field=models.BooleanField(default=False, help_text='Enable force control for vacuum'),
        ),
    ]
