# Generated by Django 5.2.9 on 2026-01-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0011_toolpathparameters_vacuum_force_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_pos_supv_dist',
            field=models.IntegerField(default=100, help_text='Polisher position supervision distance (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_workzone',
            field=models.CharField(default='bed', help_text='Polisher workzone: panel or bed', max_length=20),
        ),
    ]
