# Generated by Django 5.2.9 on 2026-01-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0012_toolpathparameters_polisher_pos_supv_dist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_workzone',
            field=models.CharField(default='panel', help_text='Helicopter workzone: panel or bed', max_length=20),
        ),
    ]
