# Generated by Django 5.2.9 on 2026-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0013_toolpathparameters_heli_workzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_pattern',
            field=models.CharField(default='serpentine', help_text='Helicopter pattern', max_length=50),
        ),
    ]
