# Generated by Django 5.2.9 on 2026-01-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0014_toolpathparameters_heli_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_pattern',
            field=models.CharField(default='serpentine', help_text='Pan pattern', max_length=50),
        ),
    ]
