# Generated by Django 5.2.9 on 2026-02-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0015_toolpathparameters_pan_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_pattern',
            field=models.CharField(default='serpentine', help_text='Polisher pattern', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='polisher_force_change',
            field=models.IntegerField(default=100, help_text='Polisher force change (N)'),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='polisher_motion_force',
            field=models.IntegerField(default=300, help_text='Polisher motion force (N)'),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='polisher_start_force',
            field=models.IntegerField(default=300, help_text='Polisher start force (N)'),
        ),
    ]
