# Generated by Django 5.2.9 on 2026-02-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0016_toolpathparameters_polisher_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='polisher_pattern',
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_first_direction',
            field=models.CharField(default='x', help_text='Polisher first pass direction: x or y', max_length=10),
        ),
    ]
