# Generated by Django 5.2.9 on 2026-02-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0017_remove_toolpathparameters_polisher_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_pattern',
            field=models.CharField(default='cross-hatch', help_text='Polisher pattern', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='heli_pattern',
            field=models.CharField(default='cross-hatch', help_text='Helicopter pattern', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='pan_pattern',
            field=models.CharField(default='cross-hatch', help_text='Pan pattern', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolpathparameters',
            name='vacuum_pattern',
            field=models.CharField(default='cross-hatch', help_text='Vacuum pattern', max_length=50),
        ),
    ]
