# Generated by Django 5.2.9 on 2026-02-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0018_add_polisher_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_speed',
            field=models.IntegerField(default=100, help_text='Polisher travel speed (mm/s)'),
        ),
    ]
