# Generated by Django 4.2.27 on 2026-02-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0019_add_polisher_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_force',
            field=models.IntegerField(default=0, help_text='Pan force (N, 0=off, 100-500)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_force_change',
            field=models.IntegerField(default=100, help_text='Pan force change rate (N)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_pos_supv_dist',
            field=models.IntegerField(default=125, help_text='Pan position supervision distance (mm)'),
        ),
    ]
