# Generated by Django 4.2.27 on 2026-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0020_add_pan_force_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='vacuum_z_max',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='vacuum_z_min',
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_z_range',
            field=models.IntegerField(default=30, help_text='Vacuum Z range around offset (+/- mm)'),
        ),
    ]
