# Generated by Django 4.2.27 on 2026-02-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot_control", "0021_consolidate_vacuum_z_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolpathparameters",
            name="heli_spiral_direction",
            field=models.CharField(
                default="anticlockwise",
                help_text="Rectangular spiral direction: clockwise or anticlockwise",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="toolpathparameters",
            name="heli_formwork_offset",
            field=models.IntegerField(
                default=100,
                help_text="Rectangular spiral formwork offset from edges (mm)",
            ),
        ),
    ]
