# Generated by Django 5.2.9 on 2026-02-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0022_add_heli_spiral_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='polisher_first_direction',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='vacuum_z_range',
        ),
    ]
