# Generated by Django 5.2.9 on 2026-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0023_remove_unused_tool_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_blade_direction',
            field=models.CharField(default='FWD', help_text='Helicopter blade direction: FWD or REV', max_length=10),
        ),
    ]
