# Generated by Django 4.2.27 on 2026-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0024_add_heli_blade_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_direction',
            field=models.IntegerField(default=1, help_text='Helicopter sweep direction: 1=L→R, -1=R→L'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_offset_x',
            field=models.IntegerField(default=100, help_text='Helicopter X offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_offset_y',
            field=models.IntegerField(default=100, help_text='Helicopter Y offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_start_bottom',
            field=models.BooleanField(default=True, help_text='Helicopter start at bottom'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_direction',
            field=models.IntegerField(default=1, help_text='Pan sweep direction: 1=L→R, -1=R→L'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_offset_x',
            field=models.IntegerField(default=100, help_text='Pan X offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_offset_y',
            field=models.IntegerField(default=100, help_text='Pan Y offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_start_bottom',
            field=models.BooleanField(default=True, help_text='Pan start at bottom'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_direction',
            field=models.IntegerField(default=1, help_text='Polisher sweep direction: 1=L→R, -1=R→L'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_offset_x',
            field=models.IntegerField(default=100, help_text='Polisher X offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_offset_y',
            field=models.IntegerField(default=100, help_text='Polisher Y offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_start_bottom',
            field=models.BooleanField(default=True, help_text='Polisher start at bottom'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_direction',
            field=models.IntegerField(default=1, help_text='Vacuum sweep direction: 1=L→R, -1=R→L'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_offset_x',
            field=models.IntegerField(default=100, help_text='Vacuum X offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_offset_y',
            field=models.IntegerField(default=100, help_text='Vacuum Y offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_start_bottom',
            field=models.BooleanField(default=True, help_text='Vacuum start at bottom'),
        ),
    ]
