# Generated by Django 4.2.27 on 2026-02-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0025_add_per_tool_crosshatch_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_formwork_offset',
            field=models.IntegerField(default=100, help_text='Pan spiral formwork offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_spiral_direction',
            field=models.CharField(default='anticlockwise', help_text='Pan spiral direction: clockwise or anticlockwise', max_length=20),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_formwork_offset',
            field=models.IntegerField(default=100, help_text='Polisher spiral formwork offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_spiral_direction',
            field=models.CharField(default='anticlockwise', help_text='Polisher spiral direction: clockwise or anticlockwise', max_length=20),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_formwork_offset',
            field=models.IntegerField(default=100, help_text='Vacuum spiral formwork offset from edges (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_spiral_direction',
            field=models.CharField(default='anticlockwise', help_text='Vacuum spiral direction: clockwise or anticlockwise', max_length=20),
        ),
    ]
