# Generated by Django 4.2.27 on 2026-02-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0026_add_spiral_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='heli_offset_x',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='heli_offset_y',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='pan_offset_x',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='pan_offset_y',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='polisher_offset_x',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='polisher_offset_y',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='vacuum_offset_x',
        ),
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='vacuum_offset_y',
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_diameter',
            field=models.IntegerField(default=1150, help_text='Helicopter tool diameter (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_overhang',
            field=models.IntegerField(default=50, help_text='Helicopter edge overhang (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_diameter',
            field=models.IntegerField(default=600, help_text='Pan tool diameter (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_overhang',
            field=models.IntegerField(default=50, help_text='Pan edge overhang (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_diameter',
            field=models.IntegerField(default=450, help_text='Polisher tool diameter (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_overhang',
            field=models.IntegerField(default=50, help_text='Polisher edge overhang (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_diameter',
            field=models.IntegerField(default=500, help_text='Vacuum tool diameter (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_overhang',
            field=models.IntegerField(default=50, help_text='Vacuum edge overhang (mm)'),
        ),
    ]
