# Generated by Django 4.2.27 on 2026-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0027_replace_offset_with_diameter_overhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_axis_5',
            field=models.IntegerField(default=0, help_text='Vacuum axis 5 tilt angle (degrees)'),
        ),
    ]
