# Generated by Django 4.2.27 on 2026-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0028_add_vacuum_axis_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='screed_edge_offset',
            field=models.IntegerField(default=200, help_text='Screed edge offset (mm) - positive extends beyond panel edges'),
        ),
    ]
