# Generated by Django 4.2.27 on 2026-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0029_add_screed_edge_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='hard_y_offset',
            field=models.IntegerField(default=0, help_text='Hard Y offset (mm) - absolute minimum Y bound for all tools'),
        ),
    ]
