# Generated by Django 5.2.9 on 2026-02-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0030_add_hard_y_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_diameter',
            field=models.IntegerField(default=450, help_text='Trowel tool diameter (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_direction',
            field=models.IntegerField(default=1, help_text='Trowel sweep direction: 1=L→R, -1=R→L'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_force',
            field=models.IntegerField(default=0, help_text='Trowel force (N, 0=off)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_formwork_offset',
            field=models.IntegerField(default=100, help_text='Trowel spiral formwork offset (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_overhang',
            field=models.IntegerField(default=50, help_text='Trowel edge overhang (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_pass_1_angle',
            field=models.IntegerField(default=0, help_text='Trowel pass 1 angle (degrees)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_pass_1_rotation',
            field=models.IntegerField(default=0, help_text='Trowel pass 1 rotation (degrees)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_pass_2_angle',
            field=models.IntegerField(default=0, help_text='Trowel pass 2 angle (degrees)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_pass_2_rotation',
            field=models.IntegerField(default=0, help_text='Trowel pass 2 rotation (degrees)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_pattern',
            field=models.CharField(default='cross-hatch', help_text='Trowel pattern', max_length=50),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_speed',
            field=models.IntegerField(default=100, help_text='Trowel travel speed (mm/s)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_spiral_direction',
            field=models.CharField(default='anticlockwise', help_text='Trowel spiral direction', max_length=20),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_start_bottom',
            field=models.BooleanField(default=True, help_text='Trowel start at bottom'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_step',
            field=models.IntegerField(default=300, help_text='Trowel step (mm)'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='trowel_z_offset',
            field=models.IntegerField(default=0, help_text='Trowel Z offset (mm)'),
        ),
    ]
