# Generated by Django 5.2.9 on 2026-02-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0031_toolpathparameters_trowel_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpathparameters',
            name='trowel_pattern',
        ),
    ]
