# Generated by Django 5.2.9 on 2026-03-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0032_remove_toolpathparameters_trowel_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_dual_hatch',
            field=models.BooleanField(default=False, help_text='Run a second offset cross-hatch pass between the first'),
        ),
    ]
