# Generated by Django 5.2.9 on 2026-03-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0033_toolpathparameters_polisher_dual_hatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='blend_radius',
            field=models.IntegerField(default=0, help_text='Corner blend radius (mm) - 0=fine/off, or ABB zone value (z1,z5,...,z200)'),
        ),
    ]
