# Generated by Django 5.2.9 on 2026-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0034_toolpathparameters_blend_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='desc_asc_blend',
            field=models.IntegerField(default=0, help_text='Descent/ascent blend radius (mm) - 0=fine/off, or ABB zone value (z1,z5,...,z200)'),
        ),
    ]
