# Generated by Django 5.2.9 on 2026-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0035_add_desc_asc_blend'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpathparameters',
            name='heli_switch_hatch',
            field=models.BooleanField(default=False, help_text='Switch cross-hatch order: Y passes first, then X'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='pan_switch_hatch',
            field=models.BooleanField(default=False, help_text='Switch cross-hatch order: Y passes first, then X'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='polisher_switch_hatch',
            field=models.BooleanField(default=False, help_text='Switch cross-hatch order: Y passes first, then X'),
        ),
        migrations.AddField(
            model_name='toolpathparameters',
            name='vacuum_switch_hatch',
            field=models.BooleanField(default=False, help_text='Switch cross-hatch order: Y passes first, then X'),
        ),
    ]
