# Generated by Django 4.2.27 on 2026-02-23 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('pm1', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='air_quality.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
